#!/bin/sh
echo "instance name       | node_len| alter | few   | many  | none  | some"
python main.py -i ../data/common-1-20.txt      -nsmfal
python main.py -i ../data/common-1-50.txt      -nsmfal
python main.py -i ../data/common-1-100.txt     -nsmfal
python main.py -i ../data/common-1-250.txt     -nsmfal
python main.py -i ../data/common-1-1000.txt    -nsmfal
python main.py -i ../data/common-1-1500.txt    -nsmfal
python main.py -i ../data/common-1-2000.txt    -nsmfal
python main.py -i ../data/common-1-2500.txt    -nsfal
python main.py -i ../data/common-1-3000.txt    -nsfal
python main.py -i ../data/common-1-3500.txt    -nsfal
python main.py -i ../data/common-1-4000.txt    -nfal
python main.py -i ../data/common-1-4500.txt    -nfal
python main.py -i ../data/common-1-5000.txt    -nfal
python main.py -i ../data/common-1-5757.txt    -nfal
python main.py -i ../data/common-2-20.txt      -nsmfal
python main.py -i ../data/common-2-50.txt      -nsmfal
python main.py -i ../data/common-2-100.txt     -nsmfal
python main.py -i ../data/common-2-250.txt     -nsmfal
python main.py -i ../data/common-2-1000.txt    -nsalf
python main.py -i ../data/common-2-1500.txt    -nsalf
python main.py -i ../data/common-2-2000.txt    -nsalf
python main.py -i ../data/common-2-2500.txt    -nsalf
python main.py -i ../data/common-2-3000.txt    -nsalf
python main.py -i ../data/common-2-3500.txt    -nsalf
python main.py -i ../data/common-2-4000.txt    -nalf
python main.py -i ../data/common-2-4500.txt    -nalf
python main.py -i ../data/common-2-5000.txt    -nalf
python main.py -i ../data/common-2-5757.txt    -nalf
python main.py -i ../data/dodecahedron.txt     -nsmfal
python main.py -i ../data/G-ex.txt             -nsmfal
python main.py -i ../data/gnm-10-15-0.txt      -nsmalf
python main.py -i ../data/gnm-10-15-1.txt      -nsmalf
python main.py -i ../data/gnm-10-20-0.txt      -nsmalf
python main.py -i ../data/gnm-10-20-1.txt      -nsmalf
python main.py -i ../data/gnm-1000-1500-0.txt  -nsalf
python main.py -i ../data/gnm-1000-1500-1.txt  -nsalf
python main.py -i ../data/gnm-1000-2000-0.txt  -nsalf
python main.py -i ../data/gnm-1000-2000-1.txt  -nsalf
python main.py -i ../data/gnm-2000-3000-0.txt  -nsalf
python main.py -i ../data/gnm-2000-3000-1.txt  -nsalf
python main.py -i ../data/gnm-2000-4000-0.txt  -nsalf
python main.py -i ../data/gnm-2000-4000-1.txt  -nsalf
python main.py -i ../data/gnm-3000-4500-0.txt  -nalf
python main.py -i ../data/gnm-3000-4500-1.txt  -nalf
python main.py -i ../data/gnm-3000-6000-0.txt  -nalf
python main.py -i ../data/gnm-3000-6000-1.txt  -nalf
python main.py -i ../data/gnm-4000-6000-0.txt  -nalf
python main.py -i ../data/gnm-4000-6000-1.txt  -nalf
python main.py -i ../data/gnm-4000-8000-0.txt  -nalf
python main.py -i ../data/gnm-4000-8000-1.txt  -nalf
python main.py -i ../data/gnm-5000-7500-0.txt  -nalf
python main.py -i ../data/gnm-5000-7500-1.txt  -nalf
python main.py -i ../data/gnm-5000-10000-0.txt -nalf
python main.py -i ../data/gnm-5000-10000-1.txt -nalf
python main.py -i ../data/grid-5-0.txt         -nsalf
python main.py -i ../data/grid-5-1.txt         -nsalf
python main.py -i ../data/grid-5-2.txt         -nsalf
python main.py -i ../data/grid-10-0.txt        -nsalf
python main.py -i ../data/grid-10-1.txt        -nsalf
python main.py -i ../data/grid-10-2.txt        -nsalf
python main.py -i ../data/grid-25-0.txt        -nalf
python main.py -i ../data/grid-25-1.txt        -nalf
python main.py -i ../data/grid-25-2.txt        -nalf
python main.py -i ../data/grid-50-0.txt        -nalf
python main.py -i ../data/grid-50-1.txt        -nalf
python main.py -i ../data/grid-50-2.txt        -nalf
python main.py -i ../data/increase-n8-1.txt    -nsmfal
python main.py -i ../data/increase-n8-2.txt    -nsmfal
python main.py -i ../data/increase-n8-3.txt    -nsmfal
python main.py -i ../data/increase-n10-1.txt   -nsmfal
python main.py -i ../data/increase-n10-2.txt   -nsmfal
python main.py -i ../data/increase-n10-3.txt   -nsmfal
python main.py -i ../data/increase-n20-1.txt   -nsmfal
python main.py -i ../data/increase-n20-2.txt   -nsmfal
python main.py -i ../data/increase-n20-3.txt   -nsmfal
python main.py -i ../data/increase-n50-1.txt   -nsmfal
python main.py -i ../data/increase-n50-2.txt   -nsmfal
python main.py -i ../data/increase-n50-3.txt   -nsmfal
python main.py -i ../data/increase-n100-1.txt  -nsmfal
python main.py -i ../data/increase-n100-2.txt  -nsfal
python main.py -i ../data/increase-n100-3.txt  -nsfmal
python main.py -i ../data/increase-n500-1.txt  -nsalf
python main.py -i ../data/increase-n500-2.txt  -nsalf
python main.py -i ../data/increase-n500-3.txt  -nsalf
python main.py -i ../data/P3.txt               -nsmfal
python main.py -i ../data/rusty-1-17.txt       -nsmalf
python main.py -i ../data/rusty-1-2000.txt     -nsmalf
python main.py -i ../data/rusty-1-2500.txt     -nalf
python main.py -i ../data/rusty-1-3000.txt     -nalf
python main.py -i ../data/rusty-1-3500.txt     -nalf
python main.py -i ../data/rusty-1-4000.txt     -nalf
python main.py -i ../data/rusty-1-4500.txt     -nalf
python main.py -i ../data/rusty-1-5000.txt     -nalf
python main.py -i ../data/rusty-1-5757.txt     -nalf
python main.py -i ../data/rusty-2-2000.txt     -nsmalf
python main.py -i ../data/rusty-2-2500.txt     -nalf
python main.py -i ../data/rusty-2-3000.txt     -nalf
python main.py -i ../data/rusty-2-3500.txt     -nalf
python main.py -i ../data/rusty-2-4000.txt     -nalf
python main.py -i ../data/rusty-2-4500.txt     -nalf
python main.py -i ../data/rusty-2-5000.txt     -nalf
python main.py -i ../data/rusty-2-5757.txt     -nalf
python main.py -i ../data/rusty-1-2000.txt     -nsmalf
python main.py -i ../data/rusty-1-2500.txt     -nalf
python main.py -i ../data/rusty-1-3000.txt     -nalf
python main.py -i ../data/rusty-1-3500.txt     -nalf
python main.py -i ../data/rusty-1-4000.txt     -nalf
python main.py -i ../data/rusty-1-4500.txt     -nalf
python main.py -i ../data/rusty-1-5000.txt     -nalf
python main.py -i ../data/ski-illustration.txt -nsmfal
python main.py -i ../data/ski-level3-1.txt     -nsmfal
python main.py -i ../data/ski-level3-2.txt     -nsmfal
python main.py -i ../data/ski-level3-3.txt     -nsmfal
python main.py -i ../data/ski-level5-1.txt     -nsmfal
python main.py -i ../data/ski-level5-2.txt     -nsmfal
python main.py -i ../data/ski-level5-3.txt     -nsmfal
python main.py -i ../data/ski-level10-1.txt    -nsmfal
python main.py -i ../data/ski-level10-2.txt    -nsmfal
python main.py -i ../data/ski-level10-3.txt    -nsmfal
python main.py -i ../data/ski-level20-1.txt    -nsmfal
python main.py -i ../data/ski-level20-2.txt    -nsmfal
python main.py -i ../data/ski-level20-3.txt    -nsmfal
python main.py -i ../data/smallworld-3-0.txt   -nsmalf
python main.py -i ../data/smallworld-3-1.txt   -nsmalf
python main.py -i ../data/smallworld-10-0.txt  -nsalf
python main.py -i ../data/smallworld-10-1.txt  -nsalf
python main.py -i ../data/smallworld-20-0.txt  -nsalf
python main.py -i ../data/smallworld-20-1.txt  -nsalf
python main.py -i ../data/smallworld-30-0.txt  -nsalf
python main.py -i ../data/smallworld-30-1.txt  -nsalf
python main.py -i ../data/smallworld-40-0.txt  -nalf
python main.py -i ../data/smallworld-40-1.txt  -nalf
python main.py -i ../data/smallworld-50-0.txt  -nsalf
python main.py -i ../data/smallworld-50-1.txt  -nsalf
python main.py -i ../data/wall-n-1.txt         -nsmalf
python main.py -i ../data/wall-n-2.txt         -nsmalf
python main.py -i ../data/wall-n-3.txt         -nsmalf
python main.py -i ../data/wall-n-4.txt         -nsmalf
python main.py -i ../data/wall-n-10.txt        -nsmalf
python main.py -i ../data/wall-n-100.txt       -nalf
python main.py -i ../data/wall-n-1000.txt      -nalf
python main.py -i ../data/wall-n-10000.txt     -nalf
python main.py -i ../data/wall-p-1.txt         -nsmalf
python main.py -i ../data/wall-p-2.txt         -nsmalf
python main.py -i ../data/wall-p-3.txt         -nsmalf
python main.py -i ../data/wall-p-4.txt         -nsmalf
python main.py -i ../data/wall-p-10.txt        -nsmalf
python main.py -i ../data/wall-p-100.txt       -nalf
python main.py -i ../data/wall-p-1000.txt      -nalf
python main.py -i ../data/wall-p-10000.txt     -nalf
python main.py -i ../data/wall-z-1.txt         -nsmalf
python main.py -i ../data/wall-z-2.txt         -nsmalf
python main.py -i ../data/wall-z-3.txt         -nsmalf
python main.py -i ../data/wall-z-4.txt         -nsmalf
python main.py -i ../data/wall-z-10.txt        -nsmalf
python main.py -i ../data/wall-z-100.txt       -nalf
python main.py -i ../data/wall-z-1000.txt      -nalf
python main.py -i ../data/wall-z-10000.txt     -nalf